extends SceneTree

const DuelPlayer = preload("res://scripts/duel_player.gd")


func _init() -> void:
	var player := DuelPlayer.new()
	player.begin_action("attack")
	assert(player.action_phase == "anticipation")
	player.advance_action(0.08)
	assert(player.action_phase == "active")
	assert(player.action_can_hit())
	player.advance_action(0.12)
	assert(player.action_phase == "recovery")
	assert(not player.action_can_hit())
	player.clear_action()
	player.begin_action("parry")
	player.advance_action(0.04)
	assert(player.action_can_parry())
	player.advance_action(0.15)
	assert(player.action_can_parry())
	player.clear_action()
	assert(player.begin_action("evade"))
	player.advance_action(0.08)
	assert(player.action == "evade")
	assert(player.action_can_evade())
	player.begin_action("attack")
	player.advance_action(0.04)
	assert(player.begin_action("parry"))
	assert(player.action == "parry")
	assert(player.action_phase == "anticipation")
	assert(player.begin_action("evade"))
	assert(player.action == "evade")
	assert(player.step_time > 0.0)
	assert(player.begin_action("jump"))
	assert(player.jump_velocity == 360.0)
	player.cut_jump()
	assert(player.jump_velocity == 180.0)
	player.free()
	print("action_timing_test: passed")
	quit()
